version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - misspell
    - forbidigo
    - dupl
    - unparam
    - nakedret
    - nestif
    - prealloc
    - dogsled
    - whitespace
    - musttag
    - bodyclose
    - fatcontext
    - noctx
    - perfsprint
    - rowserrcheck
    - sqlclosecheck

formatters:
  enable:
    - goimports
    - gofumpt
    - golines

  settings:
    goimports:
      local-prefixes:
        - <package_name>

run:
  timeout: 5m
  tests: true
