services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - DB_HOST=host.docker.internal
    restart: unless-stopped  
  
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    networks:
      - app-network


volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
